### ISSUE TITLE
Height constraints on logo overlays

### ISSUE THREAD

**Issue by alkiko** [cinemataztic/gatsby-theme-cinemataztic-cms#11]
Sæt fx 20vh og 100%. 

Mobile:
![image](https://user-images.githubusercontent.com/6972570/115837963-73de0580-a419-11eb-8ef8-1eda37acf14b.jpeg)

![image](https://user-images.githubusercontent.com/6972570/115837971-77718c80-a419-11eb-818c-ce9b6febd0f6.jpeg)

**Comment by anders-sondergaard** [comment]
Skal se sådan ud:
![Uploading Screenshot 2021-04-23 at 09.56.37.png…]()

**Comment by anders-sondergaard** [comment]
![Screenshot 2021-04-23 at 09 56 37](https://user-images.githubusercontent.com/75014940/115849808-8b22f000-a425-11eb-8d8e-59f14ee6f32e.png)
